"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "@/app/operational.module.css";
import type { BacktestEquityPoint, BacktestPricePoint, BacktestTrade, StockBacktestReport } from "@/lib/backtest";

const percent=(v:number|null,d=2)=>v===null?"—":`${(v*100).toFixed(d)}%`;const number=(v:number|null,d=2)=>v===null?"—":v.toFixed(d);const money=(v:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",maximumFractionDigits:0}).format(v);

export default function BacktestWorkspace({symbol,endDate}:{symbol:string;endDate:string}){
  const[report,setReport]=useState<StockBacktestReport|null>(null);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[selectedTrade,setSelectedTrade]=useState<number|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch("/api/backtests/stock",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.signal,body:JSON.stringify({symbol,endDate:endDate||undefined,strategyId:"pullback-strength-stock",strategyVersion:"0.4",parameterVersion:"0.4-current",testProfile:"stock-two-year-v1"})}).then(async(r)=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"回测失败");return p.data as StockBacktestReport}).then(setReport).catch((e)=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[endDate,symbol]);
  if(loading)return <main className={styles.page}><div className={styles.shell}><div className={styles.loadingTicket}><div className={styles.loadingMark}/><h1>正在重建近两年信号与成交</h1><p>读取预热行情 → 每日评分 → T+1 成交 → 净值与指标</p></div></div></main>;
  if(error||!report)return <main className={styles.page}><div className={styles.shell}><div className={styles.errorTicket}><h1>回测未完成</h1><p>{error}</p><Link className={`${styles.linkButton} ${styles.backLink}`} href={`/evaluate?symbol=${symbol}`}>返回个股评分</Link></div></div></main>;
  const m=report.metrics;const key=[["年化收益",percent(m.annualizedReturn)],["最大回撤",percent(m.maxDrawdown)],["Sharpe",number(m.sharpe)],["Calmar",number(m.calmar)]];const other=[["累计收益",percent(m.cumulativeReturn)],["胜率",percent(m.winRate)],["盈亏比",number(m.profitLossRatio)],["交易次数",String(m.tradeCount)],["平均持仓",m.averageHoldingDays===null?"—":`${m.averageHoldingDays.toFixed(1)}日`],["年化波动",percent(m.annualizedVolatility)],["最大连亏",`${m.maxConsecutiveLosses}笔`],["盈利因子",number(m.profitFactor)],["平均 R",number(m.averageR)],["平均资金使用",percent(m.averageUtilization)],["同期买入持有",percent(m.buyAndHoldReturn)]];
  return <main className={styles.page}><div className={styles.shell}>
    <header className={styles.backtestHeader}><div><p className={styles.eyebrow}>固定规则历史回执</p><h1>{report.name}<span>{report.symbol}</span></h1><p>{report.startDate} 至 {report.endDate} · {report.tradingDays} 个交易日 · 预热 {report.warmupBars} 条</p></div><Link className={`${styles.linkButton} ${styles.backLink}`} href={`/evaluate?symbol=${report.symbol.split('.')[0]}&signalDate=${report.endDate}`}>返回个股评分</Link></header>
    <div className={styles.metaStrip}><span>策略 {report.strategyVersion}</span><span>参数 {report.parameterVersion}</span><span>{report.provider}</span><span>{report.adjustment}</span><span>佣金 0.03%（最低5元）</span><span>卖出印花税 0.05%</span><span>单边滑点 0.10%</span></div>{m.tradeCount<10?<div className={styles.sampleWarning}>样本不足 10 笔，结果仅用于检查规则执行，不能据此描述策略质量。</div>:null}
    <BackSection title="价格与实际买卖点" note="买卖点使用方向、文字和形状区分；点击交易明细可高亮。"><PriceChart prices={report.priceSeries} trades={report.trades} selectedTrade={selectedTrade}/></BackSection>
    <BackSection title="核心结果" note="所有指标与交易明细使用同一条日净值序列。"><div className={styles.backMetricGrid}>{key.map(([l,v])=><Metric key={l} label={l} value={v}/>)}</div><div className={`${styles.backMetricGrid} ${styles.compact}`}>{other.map(([l,v])=><Metric key={l} label={l} value={v}/>)}</div></BackSection>
    <BackSection title="策略净值与回撤" note={`最大回撤区间：${m.maxDrawdownStart??"—"} 至 ${m.maxDrawdownEnd??"—"}`}><EquityChart points={report.equityCurve}/></BackSection>
    <BackSection title="交易明细" note="按入场时间升序；期末持仓按期末结算计入。"><TradeTable trades={report.trades} selected={selectedTrade} setSelected={setSelectedTrade}/></BackSection>
    <BackSection title="规则执行摘要" note="拒绝原因按出现次数降序。"><div className={styles.ruleSummary}><div><span>历史信号</span><strong>{report.signalCount}</strong></div><div><span>成功入场 / 被取消</span><strong>{report.trades.length} / {report.cancelledSignalCount}</strong></div><div>{report.rejectionCounts.slice(0,5).map(i=><div className={styles.rejection} key={i.reason}><span>{i.reason}</span><b>{i.count}</b></div>)}</div></div></BackSection>
    <p className={styles.footerNote}>结果生成于 {new Date(report.generatedAt).toLocaleString("zh-CN")}。历史回测不代表未来收益，评分不等于上涨概率。</p>
  </div></main>;
}

function BackSection({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className={`${styles.section} ${styles.backSection}`}><header className={styles.sectionHeader}><h2>{title}</h2><p>{note}</p></header>{children}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.backMetric}><span>{label}</span><strong>{value}</strong></div>}
function scale(values:number[],height:number,padding=24){const min=Math.min(...values),max=Math.max(...values);return(v:number)=>height-padding-(v-min)/Math.max(1e-9,max-min)*(height-padding*2)}
function PriceChart({prices,trades,selectedTrade}:{prices:BacktestPricePoint[];trades:BacktestTrade[];selectedTrade:number|null}){const width=1200,height=380,y=scale(prices.map(p=>p.close),height,32),x=(date:string)=>Math.max(0,prices.findIndex(p=>p.date===date))/Math.max(1,prices.length-1)*(width-48)+24,path=prices.map((p,i)=>`${i?"L":"M"} ${x(p.date).toFixed(1)} ${y(p.close).toFixed(1)}`).join(" ");return <div className={styles.chartCoupon}><svg aria-label="近两年收盘价格与买卖点" role="img" viewBox={`0 0 ${width} ${height}`}><path d={path} fill="none" stroke="#39256F" strokeWidth="2"/>{trades.map(t=><g key={t.id} opacity={selectedTrade===null||selectedTrade===t.id?1:.2}><line stroke="#647087" strokeDasharray="4 5" x1={x(t.entryDate)} x2={x(t.exitDate)} y1={y(t.entryPrice)} y2={y(t.exitPrice)}/><path d={`M ${x(t.entryDate)-7} ${y(t.entryPrice)+10} L ${x(t.entryDate)} ${y(t.entryPrice)-2} L ${x(t.entryDate)+7} ${y(t.entryPrice)+10} Z`} fill="#246D59"/><path d={`M ${x(t.exitDate)-7} ${y(t.exitPrice)-10} L ${x(t.exitDate)} ${y(t.exitPrice)+2} L ${x(t.exitDate)+7} ${y(t.exitPrice)-10} Z`} fill="#BD2D37"/></g>)}</svg><div className={styles.chartLegend}><span>{prices[0]?.date}</span><span>▲ 买入 · ▼ 卖出</span><span>{prices.at(-1)?.date}</span></div></div>}
function EquityChart({points}:{points:BacktestEquityPoint[]}){const width=1200,height=300,x=(i:number)=>i/Math.max(1,points.length-1)*(width-48)+24,yEq=scale(points.map(p=>p.equity),190,20),eq=points.map((p,i)=>`${i?"L":"M"} ${x(i)} ${yEq(p.equity)}`).join(" "),minDd=Math.min(...points.map(p=>p.drawdown)),yDd=(v:number)=>225+(v/Math.min(-.00001,minDd))*55,dd=points.map((p,i)=>`${i?"L":"M"} ${x(i)} ${yDd(p.drawdown)}`).join(" ");return <div className={styles.chartCoupon}><svg aria-label="策略净值与回撤" role="img" viewBox={`0 0 ${width} ${height}`}><line stroke="#647087" x1="24" x2={width-24} y1="215" y2="215"/><path d={eq} fill="none" stroke="#39256F" strokeWidth="2"/><path d={`${dd} L ${width-24} 225 L 24 225 Z`} fill="#BD2D37" opacity=".35"/><text fill="#647087" fontSize="12" x="30" y="22">策略净值</text><text fill="#647087" fontSize="12" x="30" y="242">回撤</text></svg></div>}
function TradeTable({trades,selected,setSelected}:{trades:BacktestTrade[];selected:number|null;setSelected:(id:number|null)=>void}){if(!trades.length)return <div className={styles.emptyTrade}>近两年没有可执行交易；价格走势仍完整展示。</div>;return <div className={styles.tradeTable}><table><thead><tr>{["#","信号日 / 分数","买入","初始止损","卖出","结果","持仓"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{trades.map(t=><tr className={selected===t.id?styles.tradeSelected:""} key={t.id} onClick={()=>setSelected(selected===t.id?null:t.id)}><td>{t.id}</td><td>{t.signalDate}<br/><small>{t.score} / {t.technicalScore} / {t.strengthScore}</small></td><td>{t.entryDate}<br/>¥{t.entryPrice.toFixed(2)} · {t.shares}股</td><td>¥{t.initialStop.toFixed(2)}<br/><small>风险 {money(t.plannedRisk)}</small></td><td>{t.exitDate}<br/>¥{t.exitPrice.toFixed(2)} · {t.exitReason}</td><td className={t.netProfit>=0?styles.tradeGain:styles.tradeLoss}>{money(t.netProfit)}<br/><small>{percent(t.returnRate)} · {t.rMultiple.toFixed(2)}R</small></td><td>{t.holdingDays}日</td></tr>)}</tbody></table></div>}
